DROP TABLE IF EXISTS "developers" CASCADE;
-- При необходимости также:
DROP TABLE IF EXISTS "tasks" CASCADE;
DROP TABLE IF EXISTS "forms" CASCADE;
DROP TABLE IF EXISTS "teams" CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;